M48
; DRILL file {KiCad 7.0.6-0} date 2024 June 08, Saturday 16:42:38
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-08T16:42:38-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0787
%
G90
G05
T1
X4.8362Y-1.853
X5.0638Y-1.853
T2
X4.1961Y-1.7454
T0
M30
